import {
  Github,
  Linkedin,
  MessageCircle,
  Code2,
  Rocket,
  Bot,
  ShoppingCart,
  Zap,
  Database,
  Globe,
  Palette,
  TrendingUp,
  Users,
  Shield
} from 'lucide-react';

export const NAV_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'Services', href: '#services' },
  { name: 'Projects', href: '#projects' },
  { name: 'Contact', href: '#contact' },
];

export const SOCIAL_LINKS = [
  {
    name: 'LinkedIn',
    href: 'https://www.linkedin.com/in/your-profile',
    icon: Linkedin,
  },
  {
    name: 'WhatsApp (Telenor)',
    href: 'https://wa.me/923451234567',
    icon: MessageCircle,
  },
]

export const CONTACT_INFO = {
  telenor: '+92 342 1129682',
  zong: '+92 316 1234567',
  whatsappTelenor: 'https://wa.me/923451234567',
  whatsappZong: 'https://wa.me/923161234567',
  linkedin: 'https://www.linkedin.com/in/your-profile',
  email: 'hello@agency.dev',
};

export const SERVICES = [
  {
    title: 'Next.js & React Development',
    description: 'Build lightning-fast, SEO-optimized web applications with the latest Next.js 16 and React 19. Perfect for businesses that need performance and scalability.',
    icon: Code2,
    features: ['Next.js 16', 'React 19', 'TypeScript', 'SSR/SSG'],
    color: 'primary',
  },
  {
    title: 'Supabase Backend Solutions',
    description: 'Secure, scalable backend infrastructure with real-time capabilities. Get authentication, databases, and storage without the complexity.',
    icon: Database,
    features: ['Auth', 'Real-time DB', 'Storage', 'Edge Functions'],
    color: 'green',
  },
  {
    title: 'AI & Chatbot Integration',
    description: 'Automate customer support and lead generation with intelligent AI chatbots. Available 24/7 to handle inquiries and boost conversions.',
    icon: Bot,
    features: ['GPT-4/Claude', 'Custom Training', 'Automation', '24/7 Support'],
    color: 'blue',
  },
  {
    title: 'E-Commerce & Online Stores',
    description: 'Launch your online store with secure payments, inventory tracking, and optimized checkout. Start selling in days, not months.',
    icon: ShoppingCart,
    features: ['Stripe/PayPal', 'Inventory', 'Analytics', 'Multi-currency'],
    color: 'pink',
  },
  {
    title: 'Business Automation',
    description: 'Save time and reduce costs with automated workflows. From CRM integration to email sequences, let technology handle the repetitive tasks.',
    icon: Zap,
    features: ['Workflows', 'CRM', 'Lead Scoring', 'Email Automation'],
    color: 'yellow',
  },
  {
    title: 'UI/UX Design',
    description: 'Beautiful, user-friendly designs that convert visitors into customers. Every pixel crafted to enhance your brand and drive results.',
    icon: Palette,
    features: ['Figma', 'Prototypes', 'Animations', 'Design Systems'],
    color: 'purple',
  },
];

export const PROJECTS = [
  // E-Commerce Projects
  {
    id: 1,
    title: 'ShopFlow E-Commerce',
    description: 'Complete online shopping platform with AI-powered product recommendations, Stripe payments, and real-time inventory management.',
    tags: ['Next.js 16', 'Supabase', 'Stripe', 'AI'],
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&auto=format&fit=crop',
    link: 'https://shopflow-demo.vercel.app',
    github: 'https://github.com/demo/shopflow',
    category: 'E-Commerce',
    stats: { users: '50K+', revenue: '$2M+', conversion: '4.2%' },
  },
  {
    id: 2,
    title: 'LuxuryMart Fashion',
    description: 'High-end fashion e-commerce with virtual try-on, personalized styling, and global shipping integration.',
    tags: ['React', 'Node.js', 'MongoDB', 'AR'],
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&auto=format&fit=crop',
    link: 'https://luxurymart-demo.vercel.app',
    github: 'https://github.com/demo/luxurymart',
    category: 'E-Commerce',
    stats: { products: '10K+', orders: '25K+', rating: '4.9' },
  },
  {
    id: 3,
    title: 'FreshCart Grocery',
    description: 'Same-day delivery grocery platform with real-time inventory, subscription boxes, and smart reordering.',
    tags: ['Next.js', 'PostgreSQL', 'Redis', 'Maps API'],
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop',
    link: 'https://freshcart-demo.vercel.app',
    github: 'https://github.com/demo/freshcart',
    category: 'E-Commerce',
    stats: { deliveries: '100K+', stores: '500+', cities: '25' },
  },
  {
    id: 4,
    title: 'TechZone Electronics',
    description: 'Electronics marketplace with product comparisons, warranty tracking, and trade-in programs.',
    tags: ['Vue.js', 'Supabase', 'Algolia', 'Stripe'],
    image: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=800&auto=format&fit=crop',
    link: 'https://techzone-demo.vercel.app',
    github: 'https://github.com/demo/techzone',
    category: 'E-Commerce',
    stats: { SKUs: '50K+', reviews: '100K+', sales: '$5M+' },
  },
  {
    id: 5,
    title: 'ArtisanMarket Handmade',
    description: 'Marketplace for handmade goods with seller dashboards, custom orders, and global artisan network.',
    tags: ['Next.js', 'Prisma', 'Stripe Connect', 'S3'],
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e35a6?w=800&auto=format&fit=crop',
    link: 'https://artisanmarket-demo.vercel.app',
    github: 'https://github.com/demo/artisanmarket',
    category: 'E-Commerce',
    stats: { sellers: '5K+', products: '80K+', countries: '40' },
  },
  // SaaS Projects
  {
    id: 6,
    title: 'AutoBot CRM',
    description: 'Autonomous CRM system with AI chatbot integration, automated lead scoring, and intelligent follow-up sequences.',
    tags: ['React', 'Supabase', 'OpenAI', 'Automation'],
    image: 'https://images.unsplash.com/photo-1531973576160-7125cd663d86?w=800&auto=format&fit=crop',
    link: 'https://autobot-crm.vercel.app',
    github: 'https://github.com/demo/autobot-crm',
    category: 'SaaS',
    stats: { leads: '10K+', automation: '85%', growth: '300%' },
  },
  {
    id: 7,
    title: 'BookingPro SaaS',
    description: 'Complete appointment booking system for service businesses with Stripe payments and calendar sync.',
    tags: ['Next.js', 'Supabase', 'Stripe', 'Google Calendar'],
    image: 'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&auto=format&fit=crop',
    link: 'https://bookingpro-demo.vercel.app',
    github: 'https://github.com/demo/bookingpro',
    category: 'SaaS',
    stats: { bookings: '5K+/mo', businesses: '200+', rating: '4.9' },
  },
  {
    id: 8,
    title: 'InvoiceFlow Billing',
    description: 'Automated invoicing platform with recurring billing, multi-currency support, and financial reporting.',
    tags: ['React', 'Node.js', 'Stripe', 'PDF Gen'],
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&auto=format&fit=crop',
    link: 'https://invoiceflow-demo.vercel.app',
    github: 'https://github.com/demo/invoiceflow',
    category: 'SaaS',
    stats: { invoices: '500K+', volume: '$10M+', users: '2K+' },
  },
  {
    id: 9,
    title: 'TeamSync Project',
    description: 'Project management platform with real-time collaboration, Gantt charts, and resource allocation.',
    tags: ['Next.js', 'Socket.io', 'PostgreSQL', 'Redis'],
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&auto=format&fit=crop',
    link: 'https://teamsync-demo.vercel.app',
    github: 'https://github.com/demo/teamsync',
    category: 'SaaS',
    stats: { teams: '500+', projects: '10K+', tasks: '1M+' },
  },
  {
    id: 10,
    title: 'CloudDocs Storage',
    description: 'Secure document management with version control, collaboration, and advanced search capabilities.',
    tags: ['Vue.js', 'AWS S3', 'Elasticsearch', 'OCR'],
    image: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&auto=format&fit=crop',
    link: 'https://clouddocs-demo.vercel.app',
    github: 'https://github.com/demo/clouddocs',
    category: 'SaaS',
    stats: { documents: '5M+', storage: '50TB', orgs: '300+' },
  },
  // AI/ML Projects
  {
    id: 11,
    title: 'AI Support Hub',
    description: 'Enterprise AI chatbot platform handling 10K+ support tickets monthly with 95% resolution rate.',
    tags: ['GPT-4', 'Next.js', 'Supabase', 'Webhooks'],
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&auto=format&fit=crop',
    link: 'https://ai-support-hub.vercel.app',
    github: 'https://github.com/demo/ai-support',
    category: 'AI/ML',
    stats: { tickets: '10K+/mo', resolution: '95%', languages: '12' },
  },
  {
    id: 12,
    title: 'ContentGenius Writer',
    description: 'AI-powered content generation platform for marketing copy, blogs, and social media posts.',
    tags: ['OpenAI', 'Next.js', 'Tailwind', 'Stripe'],
    image: 'https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=800&auto=format&fit=crop',
    link: 'https://contentgenius-demo.vercel.app',
    github: 'https://github.com/demo/contentgenius',
    category: 'AI/ML',
    stats: { articles: '100K+', users: '15K+', words: '50M+' },
  },
  {
    id: 13,
    title: 'VisionAI Analytics',
    description: 'Computer vision platform for retail analytics, foot traffic analysis, and customer behavior insights.',
    tags: ['Python', 'TensorFlow', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&auto=format&fit=crop',
    link: 'https://visionai-demo.vercel.app',
    github: 'https://github.com/demo/visionai',
    category: 'AI/ML',
    stats: { locations: '200+', accuracy: '99.2%', insights: '1M+' },
  },
  {
    id: 14,
    title: 'PredictFlow Forecasting',
    description: 'Machine learning platform for sales forecasting, demand prediction, and inventory optimization.',
    tags: ['Python', 'scikit-learn', 'FastAPI', 'React'],
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop',
    link: 'https://predictflow-demo.vercel.app',
    github: 'https://github.com/demo/predictflow',
    category: 'AI/ML',
    stats: { predictions: '10M+', accuracy: '94%', savings: '$2M+' },
  },
  {
    id: 15,
    title: 'VoiceBot Assistant',
    description: 'Voice-enabled AI assistant for customer service with natural language understanding and multi-lingual support.',
    tags: ['Whisper', 'GPT-4', 'Twilio', 'Node.js'],
    image: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?w=800&auto=format&fit=crop',
    link: 'https://voicebot-demo.vercel.app',
    github: 'https://github.com/demo/voicebot',
    category: 'AI/ML',
    stats: { calls: '50K+/mo', satisfaction: '4.8', languages: '8' },
  },
  // Agency Projects
  {
    id: 16,
    title: 'TechAgency Pro',
    description: 'Modern agency website with booking system, portfolio showcase, and integrated contact forms.',
    tags: ['Next.js', 'Framer Motion', 'Tailwind', 'Cal.com'],
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop',
    link: 'https://techagency-pro.vercel.app',
    github: 'https://github.com/demo/techagency',
    category: 'Agency',
    stats: { leads: '100+/mo', pages: '15+', speed: '98/100' },
  },
  {
    id: 17,
    title: 'CreativeStudio Portfolio',
    description: 'Award-winning design agency portfolio with immersive animations and case study presentations.',
    tags: ['React', 'GSAP', 'Three.js', 'Sanity'],
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&auto=format&fit=crop',
    link: 'https://creativestudio-demo.vercel.app',
    github: 'https://github.com/demo/creativestudio',
    category: 'Agency',
    stats: { awards: '12', clients: '50+', projects: '200+' },
  },
  {
    id: 18,
    title: 'LawFirm Digital',
    description: 'Professional law firm website with client portal, case management, and secure document sharing.',
    tags: ['Next.js', 'Supabase', 'Stripe', 'DocuSign'],
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop',
    link: 'https://lawfirm-demo.vercel.app',
    github: 'https://github.com/demo/lawfirm',
    category: 'Agency',
    stats: { cases: '500+', clients: '1K+', satisfaction: '98%' },
  },
  {
    id: 19,
    title: 'RealEstate Luxury',
    description: 'Premium real estate platform with virtual tours, mortgage calculator, and agent dashboards.',
    tags: ['Next.js', 'Mapbox', 'Matterport', 'Supabase'],
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&auto=format&fit=crop',
    link: 'https://realestate-demo.vercel.app',
    github: 'https://github.com/demo/realestate',
    category: 'Agency',
    stats: { listings: '5K+', sales: '$50M+', agents: '100+' },
  },
  {
    id: 20,
    title: 'HealthCare Clinic',
    description: 'Medical clinic website with online booking, patient portal, and telemedicine integration.',
    tags: ['React', 'HIPAA', 'Zoom SDK', 'PostgreSQL'],
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop',
    link: 'https://healthcare-demo.vercel.app',
    github: 'https://github.com/demo/healthcare',
    category: 'Agency',
    stats: { patients: '10K+', appointments: '5K+/mo', doctors: '25' },
  },
  // FinTech Projects
  {
    id: 21,
    title: 'FinanceFlow Dashboard',
    description: 'Real-time financial analytics dashboard with automated reporting and predictive insights.',
    tags: ['React', 'D3.js', 'Python', 'Machine Learning'],
    image: 'https://images.unsplash.com/photo-1642790106117-e829e14a795f?w=800&auto=format&fit=crop',
    link: 'https://financeflow-demo.vercel.app',
    github: 'https://github.com/demo/financeflow',
    category: 'FinTech',
    stats: { transactions: '$5M+', accuracy: '99.9%', reports: '50+' },
  },
  {
    id: 22,
    title: 'CryptoTracker Pro',
    description: 'Cryptocurrency portfolio tracker with real-time prices, alerts, and tax reporting.',
    tags: ['React', 'Web3', 'CoinGecko', 'Firebase'],
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=800&auto=format&fit=crop',
    link: 'https://cryptotracker-demo.vercel.app',
    github: 'https://github.com/demo/cryptotracker',
    category: 'FinTech',
    stats: { portfolios: '25K+', tracked: '$100M+', coins: '500+' },
  },
  {
    id: 23,
    title: 'PaymentGate Processor',
    description: 'White-label payment processing platform with multi-currency support and fraud detection.',
    tags: ['Node.js', 'Stripe', 'PostgreSQL', 'Redis'],
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&auto=format&fit=crop',
    link: 'https://paymentgate-demo.vercel.app',
    github: 'https://github.com/demo/paymentgate',
    category: 'FinTech',
    stats: { processed: '$50M+', merchants: '500+', uptime: '99.99%' },
  },
  {
    id: 24,
    title: 'BudgetWise Personal',
    description: 'Personal finance app with expense tracking, budgets, savings goals, and investment insights.',
    tags: ['React Native', 'Plaid', 'Firebase', 'Charts'],
    image: 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&auto=format&fit=crop',
    link: 'https://budgetwise-demo.vercel.app',
    github: 'https://github.com/demo/budgetwise',
    category: 'FinTech',
    stats: { users: '100K+', saved: '$10M+', rating: '4.8' },
  },
  {
    id: 25,
    title: 'LendingHub Platform',
    description: 'Peer-to-peer lending platform with credit scoring, automated underwriting, and investor dashboards.',
    tags: ['Next.js', 'Python', 'ML', 'Plaid', 'Supabase'],
    image: 'https://images.unsplash.com/photo-1434626881859-194d67b2b86f?w=800&auto=format&fit=crop',
    link: 'https://lendinghub-demo.vercel.app',
    github: 'https://github.com/demo/lendinghub',
    category: 'FinTech',
    stats: { loans: '$20M+', investors: '5K+', default: '1.2%' },
  },
];

export const STATS = [
  { value: 17, suffix: '+', label: 'Projects Delivered' },
  { value: 15, suffix: '+', label: 'Happy Clients' },
  { value: 4.58, suffix: '/5', label: 'Client Rating' },
  { value: 2, suffix: 'M+', label: 'Revenue Generated' },
];

export const TESTIMONIALS = [
  {
    name: 'Sarah Johnson',
    role: 'CEO, TechStart',
    content: 'They transformed our online presence completely. Our conversions increased by 300% after the new website launch.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop',
  },
  {
    name: 'Michael Chen',
    role: 'Founder, ShopEasy',
    content: 'The e-commerce platform they built handles thousands of orders daily without any issues. Exceptional work!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop',
  },
  {
    name: 'Emma Williams',
    role: 'Marketing Director, GrowthCo',
    content: 'The AI chatbot they integrated saves us 40+ hours weekly on customer support. Game-changing technology.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop',
  },
];

export const TEAM_MEMBERS = [
  {
    name: 'Alex Rivera',
    role: 'Lead Developer',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop',
  },
  {
    name: 'Sarah Kim',
    role: 'UI/UX Designer',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop',
  },
  {
    name: 'David Chen',
    role: 'Backend Engineer',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop',
  },
  {
    name: 'Emily Johnson',
    role: 'Project Manager',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop',
  },
];

export const TECH_STACK = [
  { name: 'Next.js', icon: Globe },
  { name: 'React', icon: Code2 },
  { name: 'Supabase', icon: Database },
  { name: 'AI/ML', icon: Bot },
  { name: 'Automation', icon: Zap },
  { name: 'Analytics', icon: TrendingUp },
  { name: 'Team', icon: Users },
  { name: 'Security', icon: Shield },
];
